//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diarion.Resources.Localization {
    using System;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diarion.Core.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppTitle => ResourceManager.GetString("AppTitle", resourceCulture) ?? "Diarion";
        public static string Subtitle => ResourceManager.GetString("Subtitle", resourceCulture) ?? "Your personal emotion diary";
        public static string NoEntries => ResourceManager.GetString("NoEntries", resourceCulture) ?? "No entries";
        public static string NoEntriesDesc => ResourceManager.GetString("NoEntriesDesc", resourceCulture) ?? "Start writing your thoughts and tracking emotions right now.";
        public static string TitleLabel => ResourceManager.GetString("TitleLabel", resourceCulture) ?? "Entry Title";
        public static string TitlePlaceholder => ResourceManager.GetString("TitlePlaceholder", resourceCulture) ?? "What are you thinking about?";
        public static string EmotionLabel => ResourceManager.GetString("EmotionLabel", resourceCulture) ?? "Your Emotional State";
        public static string EmotionPlaceholder => ResourceManager.GetString("EmotionPlaceholder", resourceCulture) ?? "Choose an emotion...";
        public static string ContentLabel => ResourceManager.GetString("ContentLabel", resourceCulture) ?? "Entry Content";
        public static string ContentPlaceholder => ResourceManager.GetString("ContentPlaceholder", resourceCulture) ?? "Start writing here...";
        public static string SaveButton => ResourceManager.GetString("SaveButton", resourceCulture) ?? "Save Entry";
        public static string EditTaskTitle => ResourceManager.GetString("EditTaskTitle", resourceCulture) ?? "Edit Task";
        public static string MaxHighPriorityAlertTitle => ResourceManager.GetString("MaxHighPriorityAlertTitle", resourceCulture) ?? "Priority Limit Reached";
        public static string MaxHighPriorityAlertMessage => ResourceManager.GetString("MaxHighPriorityAlertMessage", resourceCulture) ?? "Psychologists recommend setting no more than 3 high-priority tasks per day to maintain focus and prevent burnout. Please change the priority or move tasks to another day.";
        public static string SleepLabel => ResourceManager.GetString("SleepLabel", resourceCulture) ?? "SLEEP";
        public static string SleepStartLabel => ResourceManager.GetString("SleepStartLabel", resourceCulture) ?? "Start:";
        public static string SleepEndLabel => ResourceManager.GetString("SleepEndLabel", resourceCulture) ?? "Wake up:";
        public static string SleepQualityLabel => ResourceManager.GetString("SleepQualityLabel", resourceCulture) ?? "Sleep quality:";
        public static string HealthLabel => ResourceManager.GetString("HealthLabel", resourceCulture) ?? "PHYSIOLOGY & HEALTH";
        public static string CycleDayLabel => ResourceManager.GetString("CycleDayLabel", resourceCulture) ?? "Cycle day:";
        public static string HealthStatusLabel => ResourceManager.GetString("HealthStatusLabel", resourceCulture) ?? "Health status:";
        public static string IntimateLifeLabel => ResourceManager.GetString("IntimateLifeLabel", resourceCulture) ?? "Intimate life:";
        public static string HabitsLabel => ResourceManager.GetString("HabitsLabel", resourceCulture) ?? "HABITS";
        public static string AddHabitLabel => ResourceManager.GetString("AddHabitLabel", resourceCulture) ?? "+ Add habit";
        public static string TriggersLabel => ResourceManager.GetString("TriggersLabel", resourceCulture) ?? "TRIGGERS:";
        public static string GratitudeLabel => ResourceManager.GetString("GratitudeLabel", resourceCulture) ?? "GRATITUDE:";
        public static string SoulFoodLabel => ResourceManager.GetString("SoulFoodLabel", resourceCulture) ?? "SOUL FOOD:";
        public static string AddTimeLabel => ResourceManager.GetString("AddTimeLabel", resourceCulture) ?? "Add target time";
        public static string TimeLabel => ResourceManager.GetString("TimeLabel", resourceCulture) ?? "Time:";
        public static string DailyRepeatLabel => ResourceManager.GetString("DailyRepeatLabel", resourceCulture) ?? "Repeat daily";
        public static string ProfileMenuTitle => ResourceManager.GetString("ProfileMenuTitle", resourceCulture) ?? "Personal Settings";
        public static string GeneralInfoLabel => ResourceManager.GetString("GeneralInfoLabel", resourceCulture) ?? "GENERAL INFORMATION";
        public static string NameLabel => ResourceManager.GetString("NameLabel", resourceCulture) ?? "Name:";
        public static string NamePlaceholder => ResourceManager.GetString("NamePlaceholder", resourceCulture) ?? "Your name";
        public static string GenderLabel => ResourceManager.GetString("GenderLabel", resourceCulture) ?? "Gender:";
        public static string GenderNotSpecified => ResourceManager.GetString("GenderNotSpecified", resourceCulture) ?? "Not specified";
        public static string GenderMale => ResourceManager.GetString("GenderMale", resourceCulture) ?? "Male";
        public static string GenderFemale => ResourceManager.GetString("GenderFemale", resourceCulture) ?? "Female";
        public static string GenderOther => ResourceManager.GetString("GenderOther", resourceCulture) ?? "Other";
        public static string AgeLabel => ResourceManager.GetString("AgeLabel", resourceCulture) ?? "Age:";
        public static string WeightLabel => ResourceManager.GetString("WeightLabel", resourceCulture) ?? "Weight (kg):";
        public static string HeightLabel => ResourceManager.GetString("HeightLabel", resourceCulture) ?? "Height (cm):";
        public static string MenstrualTrackingTitle => ResourceManager.GetString("MenstrualTrackingTitle", resourceCulture) ?? "MENSTRUAL CALENDAR";
        public static string EnableTrackingLabel => ResourceManager.GetString("EnableTrackingLabel", resourceCulture) ?? "Enable tracking";
        public static string CycleLengthLabel => ResourceManager.GetString("CycleLengthLabel", resourceCulture) ?? "Average cycle length (days):";
        public static string PeriodLengthLabel => ResourceManager.GetString("PeriodLengthLabel", resourceCulture) ?? "Average period length (days):";
        public static string LastPeriodDateLabel => ResourceManager.GetString("LastPeriodDateLabel", resourceCulture) ?? "Last period start date:";
        public static string PregnancyProbabilityLabel => ResourceManager.GetString("PregnancyProbabilityLabel", resourceCulture) ?? "Pregnancy probability:";
        public static string ProbLow => ResourceManager.GetString("ProbLow", resourceCulture) ?? "Low";
        public static string ProbMedium => ResourceManager.GetString("ProbMedium", resourceCulture) ?? "Medium";
        public static string ProbHigh => ResourceManager.GetString("ProbHigh", resourceCulture) ?? "High";
        public static string CycleDayFormat => ResourceManager.GetString("CycleDayFormat", resourceCulture) ?? "Day {0}";
        public static string SaveProfileButton => ResourceManager.GetString("SaveProfileButton", resourceCulture) ?? "SAVE SETTINGS";
        public static string ProfileSavedMessage => ResourceManager.GetString("ProfileSavedMessage", resourceCulture) ?? "Settings successfully saved!";
        public static string DeleteButton => ResourceManager.GetString("DeleteButton", resourceCulture) ?? "Delete Entry";
        public static string DeleteConfirmTitle => ResourceManager.GetString("DeleteConfirmTitle", resourceCulture) ?? "Confirmation";
        public static string DeleteConfirmMsg => ResourceManager.GetString("DeleteConfirmMsg", resourceCulture) ?? "Are you sure you want to delete this entry?";
        public static string DeleteConfirmYes => ResourceManager.GetString("DeleteConfirmYes", resourceCulture) ?? "Yes";
        public static string DeleteConfirmNo => ResourceManager.GetString("DeleteConfirmNo", resourceCulture) ?? "No";
        public static string AlertWarning => ResourceManager.GetString("AlertWarning", resourceCulture) ?? "Warning";
        public static string AlertError => ResourceManager.GetString("AlertError", resourceCulture) ?? "Error";
        public static string AlertEmptyContent => ResourceManager.GetString("AlertEmptyContent", resourceCulture) ?? "Entry content cannot be empty";
        public static string AlertSaveError => ResourceManager.GetString("AlertSaveError", resourceCulture) ?? "Failed to save entry";
        public static string AlertDeleteError => ResourceManager.GetString("AlertDeleteError", resourceCulture) ?? "Failed to delete entry";
        public static string NewEntryTitle => ResourceManager.GetString("NewEntryTitle", resourceCulture) ?? "New Entry";
        public static string EditEntryTitle => ResourceManager.GetString("EditEntryTitle", resourceCulture) ?? "Edit Entry";
        public static string MyEntriesTitle => ResourceManager.GetString("MyEntriesTitle", resourceCulture) ?? "My Entries";
        public static string EmotionNone => ResourceManager.GetString("EmotionNone", resourceCulture) ?? "None";
        public static string EmotionHappy => ResourceManager.GetString("EmotionHappy", resourceCulture) ?? "Happy";
        public static string EmotionCalm => ResourceManager.GetString("EmotionCalm", resourceCulture) ?? "Calm";
        public static string EmotionAnxious => ResourceManager.GetString("EmotionAnxious", resourceCulture) ?? "Anxious";
        public static string EmotionSad => ResourceManager.GetString("EmotionSad", resourceCulture) ?? "Sad";
        public static string EmotionAngry => ResourceManager.GetString("EmotionAngry", resourceCulture) ?? "Angry";
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string TodoListLabel {
            get {
                return ResourceManager.GetString("TodoListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new task....
        /// </summary>
        public static string AddTodoPlaceholder {
            get {
                return ResourceManager.GetString("AddTodoPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddTodoButton {
            get {
                return ResourceManager.GetString("AddTodoButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string PriorityLow {
            get {
                return ResourceManager.GetString("PriorityLow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string PriorityMedium {
            get {
                return ResourceManager.GetString("PriorityMedium", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string PriorityHigh {
            get {
                return ResourceManager.GetString("PriorityHigh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please save the diary entry first before adding tasks..
        /// </summary>
        public static string SaveEntryFirstWarning {
            get {
                return ResourceManager.GetString("SaveEntryFirstWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Planner.
        /// </summary>
        public static string TabPlanner {
            get {
                return ResourceManager.GetString("TabPlanner", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string TabDiary {
            get {
                return ResourceManager.GetString("TabDiary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No tasks for this day.
        /// </summary>
        public static string NoTasks {
            get {
                return ResourceManager.GetString("NoTasks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TODAY.
        /// </summary>
        public static string TodayLabel {
            get {
                return ResourceManager.GetString("TodayLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MON.
        /// </summary>
        public static string WeekdayMonShort {
            get {
                return ResourceManager.GetString("WeekdayMonShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TUE.
        /// </summary>
        public static string WeekdayTueShort {
            get {
                return ResourceManager.GetString("WeekdayTueShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WED.
        /// </summary>
        public static string WeekdayWedShort {
            get {
                return ResourceManager.GetString("WeekdayWedShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to THU.
        /// </summary>
        public static string WeekdayThuShort {
            get {
                return ResourceManager.GetString("WeekdayThuShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FRI.
        /// </summary>
        public static string WeekdayFriShort {
            get {
                return ResourceManager.GetString("WeekdayFriShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SAT.
        /// </summary>
        public static string WeekdaySatShort {
            get {
                return ResourceManager.GetString("WeekdaySatShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SUN.
        /// </summary>
        public static string WeekdaySunShort {
            get {
                return ResourceManager.GetString("WeekdaySunShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Task.
        /// </summary>
        public static string NewTaskTitle {
            get {
                return ResourceManager.GetString("NewTaskTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string TaskDescriptionLabel {
            get {
                return ResourceManager.GetString("TaskDescriptionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selected day.
        /// </summary>
        public static string TaskDateLabel {
            get {
                return ResourceManager.GetString("TaskDateLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mark as completed.
        /// </summary>
        public static string TaskCompletedLabel {
            get {
                return ResourceManager.GetString("TaskCompletedLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string TaskPriorityLabel {
            get {
                return ResourceManager.GetString("TaskPriorityLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create Task.
        /// </summary>
        public static string SaveTaskButton {
            get {
                return ResourceManager.GetString("SaveTaskButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButtonLabel {
            get {
                return ResourceManager.GetString("OkButtonLabel", resourceCulture);
            }
        }
    }
}
