//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diarion.Resources.Localization {
    using System;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diarion.Core.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppTitle => ResourceManager.GetString("AppTitle", resourceCulture) ?? "Diarion";
        public static string Subtitle => ResourceManager.GetString("Subtitle", resourceCulture) ?? "Your personal emotion diary";
        public static string NoEntries => ResourceManager.GetString("NoEntries", resourceCulture) ?? "No entries";
        public static string NoEntriesDesc => ResourceManager.GetString("NoEntriesDesc", resourceCulture) ?? "Start writing your thoughts and tracking emotions right now.";
        public static string TitleLabel => ResourceManager.GetString("TitleLabel", resourceCulture) ?? "Entry Title";
        public static string TitlePlaceholder => ResourceManager.GetString("TitlePlaceholder", resourceCulture) ?? "What are you thinking about?";
        public static string EmotionLabel => ResourceManager.GetString("EmotionLabel", resourceCulture) ?? "Your Emotional State";
        public static string EmotionPlaceholder => ResourceManager.GetString("EmotionPlaceholder", resourceCulture) ?? "Choose an emotion...";
        public static string ContentLabel => ResourceManager.GetString("ContentLabel", resourceCulture) ?? "Entry Content";
        public static string ContentPlaceholder => ResourceManager.GetString("ContentPlaceholder", resourceCulture) ?? "Start writing here...";
        public static string SaveButton => ResourceManager.GetString("SaveButton", resourceCulture) ?? "Save Entry";
        public static string EditTaskTitle => ResourceManager.GetString("EditTaskTitle", resourceCulture) ?? "Edit Task";
        public static string MaxHighPriorityAlertTitle => ResourceManager.GetString("MaxHighPriorityAlertTitle", resourceCulture) ?? "Priority Limit Reached";
        public static string MaxHighPriorityAlertMessage => ResourceManager.GetString("MaxHighPriorityAlertMessage", resourceCulture) ?? "Psychologists recommend setting no more than 3 high-priority tasks per day to maintain focus and prevent burnout. Please change the priority or move tasks to another day.";
        public static string SleepLabel => ResourceManager.GetString("SleepLabel", resourceCulture) ?? "SLEEP";
        public static string SleepStartLabel => ResourceManager.GetString("SleepStartLabel", resourceCulture) ?? "Start:";
        public static string SleepEndLabel => ResourceManager.GetString("SleepEndLabel", resourceCulture) ?? "Wake up:";
        public static string SleepQualityLabel => ResourceManager.GetString("SleepQualityLabel", resourceCulture) ?? "Sleep quality:";
        public static string HealthLabel => ResourceManager.GetString("HealthLabel", resourceCulture) ?? "PHYSIOLOGY & HEALTH";
        public static string CycleDayLabel => ResourceManager.GetString("CycleDayLabel", resourceCulture) ?? "Cycle day:";
        public static string HealthStatusLabel => ResourceManager.GetString("HealthStatusLabel", resourceCulture) ?? "Health status:";
        public static string IntimateLifeLabel => ResourceManager.GetString("IntimateLifeLabel", resourceCulture) ?? "Intimate life:";
        public static string HabitsLabel => ResourceManager.GetString("HabitsLabel", resourceCulture) ?? "HABITS";
        public static string AddHabitPromptTitle => ResourceManager.GetString("AddHabitPromptTitle", resourceCulture) ?? "New habit";
        public static string AddHabitPromptMessage => ResourceManager.GetString("AddHabitPromptMessage", resourceCulture) ?? "Enter the habit name:";
        public static string AddHabitLabel => ResourceManager.GetString("AddHabitLabel", resourceCulture) ?? "+ Add habit";
        public static string DeleteHabitConfirmTitle => ResourceManager.GetString("DeleteHabitConfirmTitle", resourceCulture) ?? "Delete habit?";
        public static string DeleteHabitConfirmMessage => ResourceManager.GetString("DeleteHabitConfirmMessage", resourceCulture) ?? "Are you sure you want to delete '{0}'? It will disappear from this day onward, but remain in previous entries.";
        public static string TriggersLabel => ResourceManager.GetString("TriggersLabel", resourceCulture) ?? "TRIGGERS:";
        public static string GratitudeLabel => ResourceManager.GetString("GratitudeLabel", resourceCulture) ?? "GRATITUDE:";
        public static string SoulFoodLabel => ResourceManager.GetString("SoulFoodLabel", resourceCulture) ?? "FOR MYSELF:";
        public static string AddTimeLabel => ResourceManager.GetString("AddTimeLabel", resourceCulture) ?? "Add target time";
        public static string TimeLabel => ResourceManager.GetString("TimeLabel", resourceCulture) ?? "Time:";
        public static string DailyRepeatLabel => ResourceManager.GetString("DailyRepeatLabel", resourceCulture) ?? "Repeat daily";
        public static string ReminderLabel => ResourceManager.GetString("ReminderLabel", resourceCulture) ?? "Enable reminder";
        public static string ProfileMenuTitle => ResourceManager.GetString("ProfileMenuTitle", resourceCulture) ?? "Personal Settings";
        public static string GeneralInfoLabel => ResourceManager.GetString("GeneralInfoLabel", resourceCulture) ?? "GENERAL INFORMATION";
        public static string NameLabel => ResourceManager.GetString("NameLabel", resourceCulture) ?? "Name:";
        public static string NamePlaceholder => ResourceManager.GetString("NamePlaceholder", resourceCulture) ?? "Your name";
        public static string GenderLabel => ResourceManager.GetString("GenderLabel", resourceCulture) ?? "Gender:";
        public static string GenderNotSpecified => ResourceManager.GetString("GenderNotSpecified", resourceCulture) ?? "Not specified";
        public static string GenderMale => ResourceManager.GetString("GenderMale", resourceCulture) ?? "Male";
        public static string GenderFemale => ResourceManager.GetString("GenderFemale", resourceCulture) ?? "Female";
        public static string GenderOther => ResourceManager.GetString("GenderOther", resourceCulture) ?? "Other";
        public static string AgeLabel => ResourceManager.GetString("AgeLabel", resourceCulture) ?? "Age:";
        public static string WeightLabel => ResourceManager.GetString("WeightLabel", resourceCulture) ?? "Weight (kg):";
        public static string HeightLabel => ResourceManager.GetString("HeightLabel", resourceCulture) ?? "Height (cm):";
        public static string MenstrualTrackingTitle => ResourceManager.GetString("MenstrualTrackingTitle", resourceCulture) ?? "MENSTRUAL CALENDAR";
        public static string EnableTrackingLabel => ResourceManager.GetString("EnableTrackingLabel", resourceCulture) ?? "Enable tracking";
        public static string CycleLengthLabel => ResourceManager.GetString("CycleLengthLabel", resourceCulture) ?? "Average cycle length (days):";
        public static string PeriodLengthLabel => ResourceManager.GetString("PeriodLengthLabel", resourceCulture) ?? "Average period length (days):";
        public static string LastPeriodDateLabel => ResourceManager.GetString("LastPeriodDateLabel", resourceCulture) ?? "Last period start date:";
        public static string PregnancyProbabilityLabel => ResourceManager.GetString("PregnancyProbabilityLabel", resourceCulture) ?? "Pregnancy probability:";
        public static string ProbLow => ResourceManager.GetString("ProbLow", resourceCulture) ?? "Low";
        public static string ProbMedium => ResourceManager.GetString("ProbMedium", resourceCulture) ?? "Medium";
        public static string ProbHigh => ResourceManager.GetString("ProbHigh", resourceCulture) ?? "High";
        public static string CycleDayFormat => ResourceManager.GetString("CycleDayFormat", resourceCulture) ?? "Day {0}";
        public static string SaveProfileButton => ResourceManager.GetString("SaveProfileButton", resourceCulture) ?? "SAVE SETTINGS";
        public static string ProfileSavedMessage => ResourceManager.GetString("ProfileSavedMessage", resourceCulture) ?? "Settings successfully saved!";
        public static string DeleteButton => ResourceManager.GetString("DeleteButton", resourceCulture) ?? "Delete Entry";
        public static string DeleteConfirmTitle => ResourceManager.GetString("DeleteConfirmTitle", resourceCulture) ?? "Confirmation";
        public static string DeleteConfirmMsg => ResourceManager.GetString("DeleteConfirmMsg", resourceCulture) ?? "Are you sure you want to delete this entry?";
        public static string DeleteConfirmYes => ResourceManager.GetString("DeleteConfirmYes", resourceCulture) ?? "Yes";
        public static string DeleteConfirmNo => ResourceManager.GetString("DeleteConfirmNo", resourceCulture) ?? "No";
        public static string AlertWarning => ResourceManager.GetString("AlertWarning", resourceCulture) ?? "Warning";
        public static string AlertError => ResourceManager.GetString("AlertError", resourceCulture) ?? "Error";
        public static string AlertEmptyContent => ResourceManager.GetString("AlertEmptyContent", resourceCulture) ?? "Entry content cannot be empty";
        public static string AlertSaveError => ResourceManager.GetString("AlertSaveError", resourceCulture) ?? "Failed to save entry";
        public static string AlertDeleteError => ResourceManager.GetString("AlertDeleteError", resourceCulture) ?? "Failed to delete entry";
        public static string NewEntryTitle => ResourceManager.GetString("NewEntryTitle", resourceCulture) ?? "New Entry";
        public static string EditEntryTitle => ResourceManager.GetString("EditEntryTitle", resourceCulture) ?? "Edit Entry";
        public static string MyEntriesTitle => ResourceManager.GetString("MyEntriesTitle", resourceCulture) ?? "My Entries";
        public static string EmotionNone => ResourceManager.GetString("EmotionNone", resourceCulture) ?? "None";
        public static string EmotionHappy => ResourceManager.GetString("EmotionHappy", resourceCulture) ?? "Happy";
        public static string EmotionCalm => ResourceManager.GetString("EmotionCalm", resourceCulture) ?? "Calm";
        public static string EmotionAnxious => ResourceManager.GetString("EmotionAnxious", resourceCulture) ?? "Anxious";
        public static string EmotionSad => ResourceManager.GetString("EmotionSad", resourceCulture) ?? "Sad";
        public static string EmotionAngry => ResourceManager.GetString("EmotionAngry", resourceCulture) ?? "Angry";
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string TodoListLabel {
            get {
                return ResourceManager.GetString("TodoListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new task....
        /// </summary>
        public static string AddTodoPlaceholder {
            get {
                return ResourceManager.GetString("AddTodoPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddTodoButton {
            get {
                return ResourceManager.GetString("AddTodoButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string PriorityLow {
            get {
                return ResourceManager.GetString("PriorityLow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string PriorityMedium {
            get {
                return ResourceManager.GetString("PriorityMedium", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string PriorityHigh {
            get {
                return ResourceManager.GetString("PriorityHigh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please save the diary entry first before adding tasks..
        /// </summary>
        public static string SaveEntryFirstWarning {
            get {
                return ResourceManager.GetString("SaveEntryFirstWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Planner.
        /// </summary>
        public static string TabPlanner {
            get {
                return ResourceManager.GetString("TabPlanner", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string TabDiary {
            get {
                return ResourceManager.GetString("TabDiary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No tasks for this day.
        /// </summary>
        public static string NoTasks {
            get {
                return ResourceManager.GetString("NoTasks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TODAY.
        /// </summary>
        public static string TodayLabel {
            get {
                return ResourceManager.GetString("TodayLabel", resourceCulture);
            }
        }

        public static string HabitTrackerTitle {
            get {
                return ResourceManager.GetString("HabitTrackerTitle", resourceCulture);
            }
        }

        public static string HabitTrackerSubtitle {
            get {
                return ResourceManager.GetString("HabitTrackerSubtitle", resourceCulture);
            }
        }

        public static string HabitTrackerSetupTitle {
            get {
                return ResourceManager.GetString("HabitTrackerSetupTitle", resourceCulture);
            }
        }

        public static string HabitTrackerSetupSubtitle {
            get {
                return ResourceManager.GetString("HabitTrackerSetupSubtitle", resourceCulture);
            }
        }

        public static string HabitTrackerNameLabel {
            get {
                return ResourceManager.GetString("HabitTrackerNameLabel", resourceCulture);
            }
        }

        public static string HabitTrackerNamePlaceholder {
            get {
                return ResourceManager.GetString("HabitTrackerNamePlaceholder", resourceCulture);
            }
        }

        public static string HabitTrackerStartDateLabel {
            get {
                return ResourceManager.GetString("HabitTrackerStartDateLabel", resourceCulture);
            }
        }

        public static string HabitTrackerAddButton {
            get {
                return ResourceManager.GetString("HabitTrackerAddButton", resourceCulture);
            }
        }

        public static string HabitTrackerEmptyState {
            get {
                return ResourceManager.GetString("HabitTrackerEmptyState", resourceCulture);
            }
        }

        public static string HabitTrackerDaysSectionTitle {
            get {
                return ResourceManager.GetString("HabitTrackerDaysSectionTitle", resourceCulture);
            }
        }

        public static string HabitTrackerMarkedDaysLabel {
            get {
                return ResourceManager.GetString("HabitTrackerMarkedDaysLabel", resourceCulture);
            }
        }

        public static string HabitTrackerNameRequiredMessage {
            get {
                return ResourceManager.GetString("HabitTrackerNameRequiredMessage", resourceCulture);
            }
        }

        public static string HabitTrackerDuplicateMessage {
            get {
                return ResourceManager.GetString("HabitTrackerDuplicateMessage", resourceCulture);
            }
        }

        public static string ReadingTrackerTitle {
            get {
                return ResourceManager.GetString("ReadingTrackerTitle", resourceCulture);
            }
        }

        public static string ReadingTrackerSubtitle {
            get {
                return ResourceManager.GetString("ReadingTrackerSubtitle", resourceCulture);
            }
        }

        public static string ReadingTrackerSlotFormat {
            get {
                return ResourceManager.GetString("ReadingTrackerSlotFormat", resourceCulture);
            }
        }

        public static string ReadingTrackerBookTitleLabel {
            get {
                return ResourceManager.GetString("ReadingTrackerBookTitleLabel", resourceCulture);
            }
        }

        public static string ReadingTrackerBookTitlePlaceholder {
            get {
                return ResourceManager.GetString("ReadingTrackerBookTitlePlaceholder", resourceCulture);
            }
        }

        public static string ReadingTrackerCompletionDateLabel {
            get {
                return ResourceManager.GetString("ReadingTrackerCompletionDateLabel", resourceCulture);
            }
        }

        public static string ReadingTrackerSaveBookButton {
            get {
                return ResourceManager.GetString("ReadingTrackerSaveBookButton", resourceCulture);
            }
        }

        public static string ReadingTrackerBookTitleRequiredMessage {
            get {
                return ResourceManager.GetString("ReadingTrackerBookTitleRequiredMessage", resourceCulture);
            }
        }

        public static string HappyMomentsTitle {
            get {
                return ResourceManager.GetString("HappyMomentsTitle", resourceCulture);
            }
        }

        public static string HappyMomentsSubtitle {
            get {
                return ResourceManager.GetString("HappyMomentsSubtitle", resourceCulture);
            }
        }

        public static string HappyMomentsSlotFormat {
            get {
                return ResourceManager.GetString("HappyMomentsSlotFormat", resourceCulture);
            }
        }

        public static string HappyMomentsFormTitle {
            get {
                return ResourceManager.GetString("HappyMomentsFormTitle", resourceCulture);
            }
        }

        public static string HappyMomentsTitleLabel {
            get {
                return ResourceManager.GetString("HappyMomentsTitleLabel", resourceCulture);
            }
        }

        public static string HappyMomentsTitlePlaceholder {
            get {
                return ResourceManager.GetString("HappyMomentsTitlePlaceholder", resourceCulture);
            }
        }

        public static string HappyMomentsDateLabel {
            get {
                return ResourceManager.GetString("HappyMomentsDateLabel", resourceCulture);
            }
        }

        public static string HappyMomentsSaveButton {
            get {
                return ResourceManager.GetString("HappyMomentsSaveButton", resourceCulture);
            }
        }

        public static string HappyMomentsTitleRequiredMessage {
            get {
                return ResourceManager.GetString("HappyMomentsTitleRequiredMessage", resourceCulture);
            }
        }

        public static string GoodDeedsTitle {
            get {
                return ResourceManager.GetString("GoodDeedsTitle", resourceCulture);
            }
        }

        public static string GoodDeedsSubtitle {
            get {
                return ResourceManager.GetString("GoodDeedsSubtitle", resourceCulture);
            }
        }

        public static string GoodDeedsSlotFormat {
            get {
                return ResourceManager.GetString("GoodDeedsSlotFormat", resourceCulture);
            }
        }

        public static string GoodDeedsFormTitle {
            get {
                return ResourceManager.GetString("GoodDeedsFormTitle", resourceCulture);
            }
        }

        public static string GoodDeedsTitleLabel {
            get {
                return ResourceManager.GetString("GoodDeedsTitleLabel", resourceCulture);
            }
        }

        public static string GoodDeedsTitlePlaceholder {
            get {
                return ResourceManager.GetString("GoodDeedsTitlePlaceholder", resourceCulture);
            }
        }

        public static string GoodDeedsDateLabel {
            get {
                return ResourceManager.GetString("GoodDeedsDateLabel", resourceCulture);
            }
        }

        public static string GoodDeedsSaveButton {
            get {
                return ResourceManager.GetString("GoodDeedsSaveButton", resourceCulture);
            }
        }

        public static string GoodDeedsTitleRequiredMessage {
            get {
                return ResourceManager.GetString("GoodDeedsTitleRequiredMessage", resourceCulture);
            }
        }

        public static string TrackerPrototypeLabel {
            get {
                return ResourceManager.GetString("TrackerPrototypeLabel", resourceCulture);
            }
        }

        public static string TrackerPreviewTitle {
            get {
                return ResourceManager.GetString("TrackerPreviewTitle", resourceCulture);
            }
        }

        public static string TrackerReadyMessage {
            get {
                return ResourceManager.GetString("TrackerReadyMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MON.
        /// </summary>
        public static string WeekdayMonShort {
            get {
                return ResourceManager.GetString("WeekdayMonShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TUE.
        /// </summary>
        public static string WeekdayTueShort {
            get {
                return ResourceManager.GetString("WeekdayTueShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WED.
        /// </summary>
        public static string WeekdayWedShort {
            get {
                return ResourceManager.GetString("WeekdayWedShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to THU.
        /// </summary>
        public static string WeekdayThuShort {
            get {
                return ResourceManager.GetString("WeekdayThuShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FRI.
        /// </summary>
        public static string WeekdayFriShort {
            get {
                return ResourceManager.GetString("WeekdayFriShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SAT.
        /// </summary>
        public static string WeekdaySatShort {
            get {
                return ResourceManager.GetString("WeekdaySatShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SUN.
        /// </summary>
        public static string WeekdaySunShort {
            get {
                return ResourceManager.GetString("WeekdaySunShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New Task.
        /// </summary>
        public static string NewTaskTitle {
            get {
                return ResourceManager.GetString("NewTaskTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string TaskDescriptionLabel {
            get {
                return ResourceManager.GetString("TaskDescriptionLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selected day.
        /// </summary>
        public static string TaskDateLabel {
            get {
                return ResourceManager.GetString("TaskDateLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Mark as completed.
        /// </summary>
        public static string TaskCompletedLabel {
            get {
                return ResourceManager.GetString("TaskCompletedLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string TaskPriorityLabel {
            get {
                return ResourceManager.GetString("TaskPriorityLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create Task.
        /// </summary>
        public static string SaveTaskButton {
            get {
                return ResourceManager.GetString("SaveTaskButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButtonLabel {
            get {
                return ResourceManager.GetString("OkButtonLabel", resourceCulture);
            }
        }

        public static string HabitPhysicalActivity {
            get {
                return ResourceManager.GetString("HabitPhysicalActivity", resourceCulture);
            }
        }

        public static string HabitWater {
            get {
                return ResourceManager.GetString("HabitWater", resourceCulture);
            }
        }

        public static string HabitVitamins {
            get {
                return ResourceManager.GetString("HabitVitamins", resourceCulture);
            }
        }

        public static string HabitReading {
            get {
                return ResourceManager.GetString("HabitReading", resourceCulture);
            }
        }

        public static string HabitSocial {
            get {
                return ResourceManager.GetString("HabitSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string StatisticsMenuTitle {
            get {
                return ResourceManager.GetString("StatisticsMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string StatisticsTitle {
            get {
                return ResourceManager.GetString("StatisticsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Duration:.
        /// </summary>
        public static string StatsSleepDuration {
            get {
                return ResourceManager.GetString("StatsSleepDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Quality:.
        /// </summary>
        public static string StatsSleepQuality {
            get {
                return ResourceManager.GetString("StatsSleepQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Emotion:.
        /// </summary>
        public static string StatsTopEmotion {
            get {
                return ResourceManager.GetString("StatsTopEmotion", resourceCulture);
            }
        }
        
        public static string StatsProductivity {
            get {
                return ResourceManager.GetString("StatsProductivity", resourceCulture);
            }
        }
        
        public static string StatsTasksCompleted {
            get {
                return ResourceManager.GetString("StatsTasksCompleted", resourceCulture);
            }
        }
        
        public static string TimeRangeWeek {
            get {
                return ResourceManager.GetString("TimeRangeWeek", resourceCulture);
            }
        }
        
        public static string TimeRangeTwoWeeks {
            get {
                return ResourceManager.GetString("TimeRangeTwoWeeks", resourceCulture);
            }
        }
        
        public static string TimeRangeMonth {
            get {
                return ResourceManager.GetString("TimeRangeMonth", resourceCulture);
            }
        }
        
        public static string TimeRange3Months {
            get {
                return ResourceManager.GetString("TimeRange3Months", resourceCulture);
            }
        }
        
        public static string TimeRange6Months {
            get {
                return ResourceManager.GetString("TimeRange6Months", resourceCulture);
            }
        }
        
        public static string TimeRangeYear {
            get {
                return ResourceManager.GetString("TimeRangeYear", resourceCulture);
            }
        }
        
        public static string FoodLabel {
            get {
                return ResourceManager.GetString("FoodLabel", resourceCulture) ?? "FOOD";
            }
        }
        
        public static string BreakfastLabel {
            get {
                return ResourceManager.GetString("BreakfastLabel", resourceCulture) ?? "Breakfast";
            }
        }
        
        public static string LunchLabel {
            get {
                return ResourceManager.GetString("LunchLabel", resourceCulture) ?? "Lunch";
            }
        }
        
        public static string DinnerLabel {
            get {
                return ResourceManager.GetString("DinnerLabel", resourceCulture) ?? "Dinner";
            }
        }
        
        public static string FoodPlaceholder {
            get {
                return ResourceManager.GetString("FoodPlaceholder", resourceCulture) ?? "What did you eat?";
            }
        }

        public static string TaskSettingsTitle {
            get {
                return ResourceManager.GetString("TaskSettingsTitle", resourceCulture) ?? "TASKS";
            }
        }

        public static string AutoMigrateTasksLabel {
            get {
                return ResourceManager.GetString("AutoMigrateTasksLabel", resourceCulture) ?? "Auto-migrate uncompleted tasks to next day";
            }
        }

        public static string WishlistTitle {
            get {
                return ResourceManager.GetString("WishlistTitle", resourceCulture) ?? "Want, Wish, Get";
            }
        }

        public static string WantLabel {
            get {
                return ResourceManager.GetString("WantLabel", resourceCulture) ?? "I Want...";
            }
        }

        public static string WishLabel {
            get {
                return ResourceManager.GetString("WishLabel", resourceCulture) ?? "I Wish...";
            }
        }

        public static string GetLabel {
            get {
                return ResourceManager.GetString("GetLabel", resourceCulture) ?? "I Will Get...";
            }
        }

        public static string FinanceTitle {
            get {
                return ResourceManager.GetString("FinanceTitle", resourceCulture) ?? "Income / Expenses";
            }
        }

        public static string TotalBalanceLabel {
            get {
                return ResourceManager.GetString("TotalBalanceLabel", resourceCulture) ?? "Total Balance";
            }
        }

        public static string MonthIncomeLabel {
            get {
                return ResourceManager.GetString("MonthIncomeLabel", resourceCulture) ?? "Income this month";
            }
        }

        public static string MonthExpenseLabel {
            get {
                return ResourceManager.GetString("MonthExpenseLabel", resourceCulture) ?? "Expenses this month";
            }
        }

        public static string IncomeLabel {
            get {
                return ResourceManager.GetString("IncomeLabel", resourceCulture) ?? "Income";
            }
        }

        public static string ExpenseLabel {
            get {
                return ResourceManager.GetString("ExpenseLabel", resourceCulture) ?? "Expense";
            }
        }

        public static string AmountPlaceholder {
            get {
                return ResourceManager.GetString("AmountPlaceholder", resourceCulture) ?? "0.00";
            }
        }

        public static string CategoryPlaceholder {
            get {
                return ResourceManager.GetString("CategoryPlaceholder", resourceCulture) ?? "Category (e.g. Salary, Groceries)";
            }
        }

        public static string NotePlaceholder {
            get {
                return ResourceManager.GetString("NotePlaceholder", resourceCulture) ?? "Note (optional)";
            }
        }

        public static string AddTransactionButton {
            get {
                return ResourceManager.GetString("AddTransactionButton", resourceCulture) ?? "Add Transaction";
            }
        }

        public static string EmptyDataMessage {
            get {
                return ResourceManager.GetString("EmptyDataMessage", resourceCulture) ?? "Not enough data for this period.";
            }
        }
    }
}

