//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diarion.Resources.Localization {
    using System;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Diarion.Core.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AppTitle => ResourceManager.GetString("AppTitle", resourceCulture) ?? "Diarion";
        public static string Subtitle => ResourceManager.GetString("Subtitle", resourceCulture) ?? "Your personal emotion diary";
        public static string NoEntries => ResourceManager.GetString("NoEntries", resourceCulture) ?? "No entries";
        public static string NoEntriesDesc => ResourceManager.GetString("NoEntriesDesc", resourceCulture) ?? "Start writing your thoughts and tracking emotions right now.";
        public static string TitleLabel => ResourceManager.GetString("TitleLabel", resourceCulture) ?? "Entry Title";
        public static string TitlePlaceholder => ResourceManager.GetString("TitlePlaceholder", resourceCulture) ?? "What are you thinking about?";
        public static string EmotionLabel => ResourceManager.GetString("EmotionLabel", resourceCulture) ?? "Your Emotional State";
        public static string EmotionPlaceholder => ResourceManager.GetString("EmotionPlaceholder", resourceCulture) ?? "Choose an emotion...";
        public static string ContentLabel => ResourceManager.GetString("ContentLabel", resourceCulture) ?? "Entry Content";
        public static string ContentPlaceholder => ResourceManager.GetString("ContentPlaceholder", resourceCulture) ?? "Start writing here...";
        public static string SaveButton => ResourceManager.GetString("SaveButton", resourceCulture) ?? "Save Entry";
        public static string DeleteButton => ResourceManager.GetString("DeleteButton", resourceCulture) ?? "Delete Entry";
        public static string DeleteConfirmTitle => ResourceManager.GetString("DeleteConfirmTitle", resourceCulture) ?? "Confirmation";
        public static string DeleteConfirmMsg => ResourceManager.GetString("DeleteConfirmMsg", resourceCulture) ?? "Are you sure you want to delete this entry?";
        public static string DeleteConfirmYes => ResourceManager.GetString("DeleteConfirmYes", resourceCulture) ?? "Yes";
        public static string DeleteConfirmNo => ResourceManager.GetString("DeleteConfirmNo", resourceCulture) ?? "No";
        public static string AlertWarning => ResourceManager.GetString("AlertWarning", resourceCulture) ?? "Warning";
        public static string AlertError => ResourceManager.GetString("AlertError", resourceCulture) ?? "Error";
        public static string AlertEmptyContent => ResourceManager.GetString("AlertEmptyContent", resourceCulture) ?? "Entry content cannot be empty";
        public static string AlertSaveError => ResourceManager.GetString("AlertSaveError", resourceCulture) ?? "Failed to save entry";
        public static string AlertDeleteError => ResourceManager.GetString("AlertDeleteError", resourceCulture) ?? "Failed to delete entry";
        public static string NewEntryTitle => ResourceManager.GetString("NewEntryTitle", resourceCulture) ?? "New Entry";
        public static string EditEntryTitle => ResourceManager.GetString("EditEntryTitle", resourceCulture) ?? "Edit Entry";
        public static string MyEntriesTitle => ResourceManager.GetString("MyEntriesTitle", resourceCulture) ?? "My Entries";
        public static string EmotionNone => ResourceManager.GetString("EmotionNone", resourceCulture) ?? "None";
        public static string EmotionHappy => ResourceManager.GetString("EmotionHappy", resourceCulture) ?? "Happy";
        public static string EmotionCalm => ResourceManager.GetString("EmotionCalm", resourceCulture) ?? "Calm";
        public static string EmotionAnxious => ResourceManager.GetString("EmotionAnxious", resourceCulture) ?? "Anxious";
        public static string EmotionSad => ResourceManager.GetString("EmotionSad", resourceCulture) ?? "Sad";
        public static string EmotionAngry => ResourceManager.GetString("EmotionAngry", resourceCulture) ?? "Angry";
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string TodoListLabel {
            get {
                return ResourceManager.GetString("TodoListLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new task....
        /// </summary>
        public static string AddTodoPlaceholder {
            get {
                return ResourceManager.GetString("AddTodoPlaceholder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddTodoButton {
            get {
                return ResourceManager.GetString("AddTodoButton", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string PriorityLow {
            get {
                return ResourceManager.GetString("PriorityLow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string PriorityMedium {
            get {
                return ResourceManager.GetString("PriorityMedium", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string PriorityHigh {
            get {
                return ResourceManager.GetString("PriorityHigh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please save the diary entry first before adding tasks..
        /// </summary>
        public static string SaveEntryFirstWarning {
            get {
                return ResourceManager.GetString("SaveEntryFirstWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Planner.
        /// </summary>
        public static string TabPlanner {
            get {
                return ResourceManager.GetString("TabPlanner", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string TabDiary {
            get {
                return ResourceManager.GetString("TabDiary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No tasks for this day.
        /// </summary>
        public static string NoTasks {
            get {
                return ResourceManager.GetString("NoTasks", resourceCulture);
            }
        }
    }
}
